# [Info]
# å·¦ä¸Šè§’æ ‡é¢˜
site_name: CosHub
site_url: https://Elliottt001.github.io
site_author: å¼ ç‘å–†
site_description: Zhang rzçš„ä¸ªäººç½‘ç«™

# [Navigtion]
nav:
  - ä¸»é¡µ: 
    - å°é¢: index.md
    - ğŸ•‘æ›´æ–°è®°å½•: changelog.md
    - ğŸ•‘å€’è®¡æ—¶: 
      - âœé«˜è€ƒå€’è®¡æ—¶: countdown/gee/gee.html
      - ğŸ‚ç”Ÿæ—¥å€’è®¡æ—¶: countdown/birthday/birthday.html

  - ä¸ªäºº:
    - ME/index.md
    - æ€è€ƒ: 
      - å¤§å­¦æ•™è‚²ä¸äººç”Ÿå‘å±•: ME/THOUGHT/colledge-education-and-my-future.md
    - SDFZ:
      - æ°¸è¿œçš„391: ME/SDFZ/391forever.md
      - é™„ä¸­å›å¿†å½•: ME/SDFZ/sdfz_memorior.md
    - ZJU:
      - é¢è¯•ç»å†: 
        - å­¦ç”Ÿä¼š: ME/ZJU/interview/interview for SU.md
        - ä¸“ä¸šç¡®è®¤: ME/ZJU/interview/interview for major.md
        - å¯çœŸé—®å­¦: ME/ZJU/interview/interview-for-qzwx.md
        - X-labé—®å·: ME/ZJU/interview/x-lab-application.md
      - è®¡åˆ’:
        - 24å¯’å‡: ME/ZJU/plan/plan-for-24winter-holiday.md
      - å­¦ä¹ :
        - èµ„æº: ME/ZJU/learn/resoure.md
    - éšç¬”:
      - 2024-11: ME/ESSAY/2024-11.md
      - 2024-12: ME/ESSAY/2024-12.md
      - 2025-01: ME/ESSAY/2025-01.md

  - æ•°ç†:
    - KNOWLEDGE/index.md
    - å¾®ç§¯åˆ†:
      - çŸ¥è¯†ä½“ç³»: KNOWLEDGE/calculus/knowledge-frame-of-calculus.md
      - æ–¹æ³•æ€»ç»“: KNOWLEDGE/calculus/summary-of-calculus.md
      - æ€æƒ³æ–¹æ³•: KNOWLEDGE/calculus/thought-for-calculus.md
      - çº§æ•°: KNOWLEDGE/calculus/series-sdk.md
      - çŸ¢é‡ä»£æ•°ä¸ç©ºé—´è§£æå‡ ä½•: KNOWLEDGE/calculus/vector-algebra.md
      - å¤šå…ƒå‡½æ•°å¾®åˆ†å­¦: KNOWLEDGE/calculus/differential-calculus-of-multivariate-function.md
    - çº¿æ€§ä»£æ•°:
      - çŸ¥è¯†ä½“ç³»: KNOWLEDGE/linear-algebra/knowledge-frame-of-LA.md
      - æ–¹æ³•æ€»ç»“: KNOWLEDGE/linear-algebra/summary-of-LA.md 
    - ç¦»æ•£æ•°å­¦:
      - Chap1 é€»è¾‘å’Œè¯æ˜: KNOWLEDGE/discrete/chap-1.md
    - å¤§å­¦ç‰©ç†:
      - å¤§é›¾ä¸‹è¯¾ç¨‹ä¿¡æ¯: KNOWLEDGE/physics/index.md
      - åŠ¨åŠ›å­¦: KNOWLEDGE/physics/dynamics-motion.md
      - ç”µç£å­¦: KNOWLEDGE/physics/electricity.md
    - æ¦‚ç‡è®ºä¸æ•°ç†ç»Ÿè®¡:
      - è¯¾ç¨‹ä¿¡æ¯: KNOWLEDGE/probability/index.md
      
  - å¼€å‘:
    - CS/index.md
    - å®æˆ˜å¼€å‘: 
      - é¡¹ç›®ç»„ç»‡: CS/develop/project.md
      - Gitè§„èŒƒ: CS/develop/git.md
      - ç¼–ç¨‹é£æ ¼: CS/develop/programming.md
    - å‰ç«¯å¼€å‘:
      - å­¦ä¹ ç¬”è®°:
        - å†…å®¹é€ŸæŸ¥: CS/front-end/note/index.md
        - webæŠ€æœ¯åŸºç¡€: CS/front-end/note/web/build.md
        - HTML: CS/front-end/note/html/tag.md
        - CSS: CS/front-end/note/css/css-note.md
      - ç¯å¢ƒé…ç½®åŠçŸ¥è¯†:
        - JavaScript: CS/front-end/note/js.md
    - åç«¯å¼€å‘:
      - å­¦ä¹ ç¬”è®°:
        - æ•°æ®åº“: CS/back-end/note/db/db.md
        - Golang: none.md
        - Java: CS/back-end/note/java/methods.md
    - ç¼–ç¨‹è¯­è¨€:
      - C/C++:
        - Cè¯­è¨€: 
          - å­¦ä¹ ç¬”è®°: CS/pl/C_Cpp/C/c-note.md
          - é”™é¢˜æ•´ç†: CS/pl/C_Cpp/C/c-errors-and-tips.md
          - é“¾è¡¨: CS/pl/C_Cpp/C/linkedList.md
        - C++:
          - è¯¾ç¨‹ä¿¡æ¯: CS/pl/C_Cpp/cpp/index.md
          - Lecture 0:Introduction: CS/pl/C_Cpp/cpp/intro.md
          - Lecture 1&2:Streams: CS/pl/C_Cpp/cpp/streams.md
          - Lecture 3:Standard Template Library: CS/pl/C_Cpp/cpp/stl.md
          - Lecture 4:Modern C++ Types: CS/pl/C_Cpp/cpp/type.md
          - Guest Lecture:Template metaprogramming: CS/pl/C_Cpp/cpp/tmp.md
          - Varibles & Synatax: CS/pl/C_Cpp/cpp/basic.md
          - Keywords: CS/pl/C_Cpp/cpp/keyword.md
      - Python:
        - pythonä¸»é¡µ: CS/pl/Python/index.md
        - åŸºç¡€è¯­æ³•: CS/pl/Python/py-basic-grammar.md
        - æ•°æ®å®¹å™¨: CS/pl/Python/py-sequence.md
        - é¢å‘å¯¹è±¡: CS/pl/Python/py-oop.md
        - æ–‡ä»¶åŸºç¡€: CS/pl/Python/file-basic.md
        - æ–‡ä»¶è¿›é˜¶: CS/pl/Python/file-advance.md
        - æ ‡å‡†åº“ç§¯ç´¯: CS/pl/Python/modules.md
        - é¡¹ç›®å¼€å‘: CS/pl/Python/development-in-py.md
        - ç™¾æ—¥æ‰“å¡: CS/pl/Python/clock-in.md
        - ä¼ŠåŠ›ç¬”è®°: CS/pl/Python/python-note.md
      - Go:
        - GORM: CS/pl/go/db.md
    - è®¡ç®—æœºç³»ç»Ÿ:
      - æ•°å­—é€»è¾‘è®¾è®¡: 
        - Chapter 1 æ•°å­—ç³»ç»Ÿä¸ä¿¡æ¯: CS/system/digital-design/chap1.md
        - Chapter 2 ç»„åˆé€»è¾‘ç”µè·¯: CS/system/digital-design/chap2.md
        - Chapter 3 ç»„åˆé€»è¾‘ç”µè·¯çš„è®¾è®¡: CS/system/digital-design/chap3.md
      - è®¡ç®—æœºç»„æˆåŸç†:
        - è¯¾ç¨‹ä¿¡æ¯: CS/system/priciples/index.md
        - Chapter 1 è®¡ç®—æœºç³»ç»Ÿæ¦‚è¿°: CS/system/priciples/chap1.md
        - æ±‡ç¼–è¯­è¨€æŒ‡ä»¤æ¦‚è¿°: CS/system/priciples/instructions.md
        - æ•°çš„è¡¨ç¤º: CS/system/priciples/number_representation.md
        
    - ç®—æ³•ç›¸å…³: 
      - æ•°æ®ç»“æ„åŸºç¡€:
        - è¯¾ç¨‹ä¿¡æ¯: CS/algorithm/fds/index.md
        - ç®—æ³•åˆ†æ: CS/algorithm/fds/chap2.md
        - Chapter 3 ADT & Stack & Queue: CS/algorithm/fds/chap3.md
        - Chapter 4 Tree: CS/algorithm/fds/chap4.md
        - Chapter 5 Graph: CS/algorithm/fds/graph.md
        - Chapter 6 Hash Table: CS/algorithm/fds/hashing.md
        - Chapter 7 Sorting: CS/algorithm/fds/sorting.md

      - é«˜çº§æ•°æ®ç»“æ„ä¸ç®—æ³•åˆ†æ:
        - è¯¾ç¨‹ä¿¡æ¯: CS/algorithm/ads/index.md
        - è€ƒè¯•å¤ä¹ ç¬”è®°: CS/algorithm/ads/exam-review.md
        - AVLæ ‘å’ŒSplayæ ‘: CS/algorithm/ads/avl-tree_splay-tree.md
        - çº¢é»‘æ ‘: CS/algorithm/ads/redblack_tree.md
        - B+æ ‘: CS/algorithm/ads/bplus_tree.md
        - å€’æ’è¡¨: CS/algorithm/ads/inverted_file_index.md
        - å·¦åæ ‘å’Œæ–œå †: CS/algorithm/ads/leftist_heap.md
        - äºŒé¡¹é˜Ÿåˆ—: CS/algorithm/ads/binomial_queue.md
        - å›æº¯æ³•: CS/algorithm/ads/backtracking.md
        - åˆ†æ²»åˆå¹¶æ³•: CS/algorithm/ads/divide_conquer.md
        - åŠ¨æ€è§„åˆ’: CS/algorithm/ads/dynamic_programming.md
      - Misc: CS/algorithm/misc.md
      - Sort: CS/algorithm/sort.md
    - æ•°æ®ç§‘å­¦:
      - å¤§æ•°æ®æŒ–æ˜:
        - è¯¾ç¨‹ä¿¡æ¯: CS/data/mining-massive-data/index.md
        - Map Reduce and Spark: CS/data/mining-massive-data/mapreduce-and-spark.md
        - Frequent Itemsets Mining: CS/data/mining-massive-data/frequent-itemsets-mining.md
        - LSH(Locality Sensitive Hashing): CS/data/mining-massive-data/lsh.md

    - æ“ä½œç³»ç»Ÿ:
      - Linux:
        - WSLå¤‡å¿˜å½•: CS/OS/linux/wsl-record.md
        - è™šæ‹Ÿæœºå¤‡å¿˜å½•: CS/OS/linux/vm-record.md
        - WSLæ“ä½œæŒ‡å—: CS/OS/linux/wsl-note.md
        - GitHub Copilot: CS/OS/linux/github-copilot.md
        - Clash Verge Rev å®‰è£…/é…ç¯å¢ƒæŒ‡å—: CS/OS/linux/clash-verge-rev.md
      - Windowsç‰©ç†æœºä¸€: CS/OS/windows/win-note.md
      - Windowsç‰©ç†æœºäºŒ: CS/OS/windows/win1.md
    - ç½‘ç»œå®‰å…¨:
      - é¦–é¡µ: CS/CTF/index.md
      - åŸºç¡€: CS/CTF/basic.md
      - CTF&AAAç®€ä»‹: CS/CTF/ctf-and-aaa.md
      - å®éªŒæŠ¥å‘Š:
        - lab0: CS/CTF/lab0.md
    - åŒºå—é“¾:
      - åŸºç¡€å¼•å…¥: CS/blockchain/background.md
      - æŠ€æœ¯åŸç†: CS/blockchain/theory.md
      - å®é™…åº”ç”¨: CS/blockchain/usage.md
      - æ¯”ç‰¹å¸: CS/blockchain/bitcoin.md
      - æ•°å­—è´§å¸: CS/blockchain/digital-currency.md
      - ä»¥å¤ªåŠ: CS/blockchain/ethereum.md
    - äººå·¥æ™ºèƒ½:
      - æœºå™¨å­¦ä¹ :
        - RUCè®²ç¨¿: CS/AI/ML/æœºå™¨å­¦ä¹ è®²ç¨¿.ipynb
      - AI: CS/AI/AI.md
      - ANN: CS/AI/ANN.md
      - DL: CS/AI/DL.md
      - ML: CS/AI/ML.md
      - Turing: CS/AI/Turing.md
    - X-lab ç›¸å…³:
      - åˆ›å§‹äººç‹æŒ¯é˜³åˆ†äº« - X-labç®€ä»‹: LAB/x-lab.md
      - å¼ åšå­¦é•¿åˆ†äº« - æ€ç»´é«˜åº¦ä¸å‰æ²¿åˆ›æ–°: LAB/zhangbo.md
      - ä»»ç‚œçƒ¨å­¦é•¿ - ä¼ä¸šçº§å¼€å‘ç»éªŒåˆ†äº«: LAB/rwy.md
      - æ±Ÿæ—ç›Šå­¦é•¿åˆ†äº« - ç§‘ç ”æ·±é€ ä¹‹è·¯: LAB/01.md
      - è½¬æ­£å¤§ä¼š: LAB/è½¬æ­£å¤§ä¼š.md
    - å®ç”¨å·¥å…·:
      - shell: 
        - ç¬”è®°ä¸€: CS/Tools/shell.md
        - ç¬”è®°äºŒ: CS/Tools/shell-new.md
      - iOS Fake Run: CS/Tools/iosfakerun.md
      - CSS: CS/Tools/CSS.md
      - HTML: CS/Tools/HTML.md
      - Git&GitHub: CS/Tools/Git & GitHub.md
      - Docker: CS/Tools/docker.md
      - Markdown: CS/Tools/Markdown(obsidian).md
      - LaTeX: CS/Tools/LaTeX.md
      - Linux: CS/Tools/Linux.md
      - vim: CS/Tools/vim.md
      - GDB: CS/Tools/GDB.md
      - Obsidian: CS/Tools/Obsidian.md
      - Mkdocs: 
        - MkDocs: CS/Tools/mkdocs.md
        - MkDocså›¾åƒ: CS/Tools/mkdocs-images-copy.md
      - Makefile: CS/Tools/makefile.md
      - Anaconda: CS/Tools/anaconda.md
      - VMware: CS/Tools/vmware-linux.md
    - æ‚ä¸ƒæ‚å…«:
      - æƒ³äº†è§£çš„ä¸œè¥¿: CS/Misc/things-i-wanna-know.md
      - æ­£åˆ™è¡¨è¾¾å¼: CS/Misc/regex.md
      - ç½‘ç»œç›¸å…³: CS/Misc/network.md
      - ä¸€äº›å¿«æ·é”®: CS/Misc/shortcuts.md
      - ç¡¬ä»¶by AI: CS/Misc/hardware.md

  - é‡‘è:
    - FINANCE/index.md
    - å¾®è§‚ç»æµå­¦:
      - è¯¾ç¨‹ä¿¡æ¯: FINANCE/micro/index.md
      - ç»ªè®º: FINANCE/micro/start.md

    - å®è§‚ç»æµå­¦:
      - è¯¾ç¨‹ä¿¡æ¯: FINANCE/macro/index.md

    - é›¶ç¢è‡ªå­¦:
      - é‡‘æœ¬ä½: FINANCE/DIY/gold-standard.md
  - é˜…è¯»:
    - BOOK/index.md
    - æ–‡å­¦åè‘—:
      - å±±èŒ¶æ–‡å…·åº—: BOOK/fictions/å±±èŒ¶æ–‡å…·åº—.md
      - æš®å…‰ä¹‹åŸ: BOOK/fictions/twilight.md
    - ä¸“ä¸šä¹¦ç±:
      - 1.md
  - å…¬ä¼—:
    - PUBLIC/index.md
    - ç§€ç±³: PUBLIC/xiumi.md
    - å“ªå’: PUBLIC/nezha.md
    - å·¥ä½œæ±‡æŠ¥: PUBLIC/work-report.md
    - æŠ¥é”€å·¥ä½œæ³¨æ„äº‹é¡¹: PUBLIC/reimbursement.md
    - ZJU-vlog: PUBLIC/zju-vlog.md

# [UI]
# [top]
theme:
  name: material

  favicon: images/favicon_circle.png
  custom_dir: overrides # ç”¨æ¥æè¯„è®ºçš„ï¼Œå‚è€ƒ https://squidfunk.github.io/mkdocs-material/setup/adding-a-comment-system/

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  font: False


  features:
    # ä½¿ç”¨ Tab æ¥è¿›è¡Œåˆ†ç±»
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-tabs
    - navigation.tabs
    # è¿”å›é¡¶éƒ¨çš„æŒ‰é’®ï¼Œåœ¨ä¸Šæ»‘æ—¶å‡ºç°
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#back-to-top-button
    - navigation.top
    # ç»™æ¯ä¸ª Tab æ·»åŠ ä¸€ä¸ª index.mdï¼Œä¸”åœ¨ç‚¹å‡» Tab æ—¶æ‰“å¼€
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages-with-section-index-pages
    - navigation.indexes
    # å³ä¾§ç›®å½•éšé¡µé¢æ»‘åŠ¨
    - toc.follow 
    # # æ‰“å¼€ Tab æ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    # # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-expansion
    # - navigation.expand
    # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-suggestions
    - search.suggest
    # æœç´¢çš„å…³é”®è¯æ–‡ç« åŠ å…¥é«˜äº®
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#search-highlighting
    - search.highlight
    # å¯ä»¥é€šè¿‡æŒ‰é’®å¤åˆ¶ä»£ç 
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # [ç‚¹å‡»æŒ‰é’®è·³è½¬è‡³ GitHub ä¿®æ”¹ Markdown æºæ–‡ä»¶]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # å°†å…¬å‘Šæ ‡è®°ä¸ºå·²è¯»
    - announce.dismiss
  icon:
    logo: material/library-outline
    # [æ·»åŠ  GitHub ä»“åº“]
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#repository-icon
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    # å—: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#admonition-icons-octicons
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      # note: fontawesome/solid/note-sticky
      # abstract: fontawesome/solid/book
      # info: fontawesome/solid/circle-info
      # tip: fontawesome/solid/bullhorn
      # success: fontawesome/solid/check
      # question: fontawesome/solid/circle-question
      # warning: fontawesome/solid/triangle-exclamation
      # failure: fontawesome/solid/bomb
      # danger: fontawesome/solid/skull
      # bug: fontawesome/solid/robot
      # example: fontawesome/solid/flask
      # quote: fontawesome/solid/quote-left
    # æ³¨é‡Š: https://squidfunk.github.io/mkdocs-material/reference/annotations/#in-content-tabs-tab-2
    annotation: material/checkbox-marked-circle-auto-outline
  
# [ç‚¹å‡»æŒ‰é’®è·³è½¬è‡³ GitHub ä¿®æ”¹ Markdown æºæ–‡ä»¶]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/
# [top-right corner]
# [æ·»åŠ  GitHub ä»“åº“]
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_url: https://github.com/Elliottt001/Elliottt001.github.io
repo_name: CosHub
# [bottom-left corner]
# [ç‰ˆæƒè¯´æ˜]
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: >
  Copyright Â© 2024 å¼ ç‘å–† All rights reserved.
  
  <a href="#__consent">Change cookie settings</a>
# [bottom-right corner]
extra:
  # [æ·»åŠ ç¤¾äº¤ç½‘ç»œå›¾æ ‡å’Œé“¾æ¥]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#social-links
  # æœç´¢å›¾æ ‡ï¼šhttps://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search
  # name ä¼šåœ¨é¼ æ ‡æ‚¬æµ®æ—¶æç¤º
  social: # icons
    - name: GitHub | Elliottt001
      icon: fontawesome/brands/github
      link: https://github.com/Elliottt001
  generator: false

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage  
  
# [Extensions]
plugins:
  # [æœç´¢åŠŸèƒ½]
  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  # ä¹‹å‰ä¸­æ–‡æœç´¢æ˜¯ Insider çš„åŠŸèƒ½ï¼ˆhttps://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/ï¼‰ï¼Œç°åœ¨å¥½åƒå·²ç»æ˜¯é»˜è®¤åŠŸèƒ½äº†ï¼Œ
  - search:
      lang:
        - zh
        - en
        - es
  # [ç»™å•ç¯‡æ–‡ç« æ·»åŠ æ ‡ç­¾]
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # https://squidfunk.github.io/mkdocs-material/plugins/tags/#meta.tags
  - tags

  - glightbox #å›¾ç‰‡æ”¾å¤§
  
  - statistics: #ç»Ÿè®¡é¡µé¢å­—æ•°ã€ä»£ ç è¡Œæ•°ã€é˜…è¯»æ—¶é—´
    #https://github.com/TonyCrane/mkdocs-statistics-plugin  
  - search
  - git-revision-date-localized

  - rss
  - search
  - git-revision-date-localized:
        type: datetime
        timezone: Asia/Shanghai
        locale: zh
        enable_creation_date: true
        exclude:
            - index.md
            - writeups/AAA.md
  - changelog
  - minify:
      minify_html: true

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 5
  - admonition #åº”ç”¨admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #æ·»åŠ äº†å¯¹å†…è”ä»£ç å—çš„è¯­æ³•çªå‡ºæ˜¾ç¤ºçš„æ”¯æŒ
  - pymdownx.snippets #ä½¿ç”¨ç®€å•è¯­æ³•å°†ä»»æ„æ–‡ä»¶çš„å†…å®¹åµŒå…¥åˆ°æ–‡æ¡£
  - pymdownx.superfences: #å…è®¸ä»£ç å’Œå†…å®¹å—ä»»æ„åµŒå¥—ï¼ŒåŒ…æ‹¬è­¦å‘Šã€é€‰é¡¹å¡ã€åˆ—è¡¨å’Œæ‰€æœ‰å…¶ä»–å…ƒç´ 
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details #admonitionå¯ä»¥æŠ˜å 

  - attr_list #å…è®¸ä½¿ç”¨ç‰¹æ®Šè¯­æ³•å°† HTML å±æ€§å’Œ CSS ç±»æ·»åŠ åˆ°å‡ ä¹æ¯ä¸ªMarkdown å†…è”å’Œå—çº§å…ƒç´ ã€‚
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.keys #æ·»åŠ äº†ä¸€ä¸ªç®€å•çš„è¯­æ³•æ¥å…è®¸å‘ˆç°é”®ç›˜æŒ‰é”®å’Œç»„åˆ 

  # Caret ã€ Markå’ŒTildeæ‰©å±•æ·»åŠ äº†ä½¿ç”¨ç®€å•è¯­æ³•çªå‡ºæ˜¾ç¤ºæ–‡æœ¬å¹¶å®šä¹‰ä¸‹æ ‡å’Œä¸Šæ ‡çš„åŠŸèƒ½ã€‚
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.critic #å…è®¸ä½¿ç”¨Critic æ ‡è®°æ¥çªå‡ºæ˜¾ç¤ºæ–‡æ¡£ä¸­æ·»åŠ ã€åˆ é™¤æˆ–æ›´æ–°çš„éƒ¨åˆ†ï¼Œå³è·Ÿè¸ª Markdown è¯­æ³•çš„æ›´æ”¹ã€‚

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  # ç›¸å…³å†…å®¹æˆ–è€…ä»£ç å—å¯ä»¥åˆ†ç»„å±•ç¤º
  - pymdownx.tabbed:
      alternate_style: true
  
  # å…è®¸ä½¿ç”¨ä»»åŠ¡æ¸…å•å³- []      
  - pymdownx.tasklist:
      custom_checkbox: true
  
  # å…è®¸æ¸²æŸ“å…¬å¼ï¼Œè¿˜éœ€è¦æ·»åŠ mathjaxé…ç½®å’ŒJavaScript      
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex
  - pymdownx.arithmatex:
      generic: true

  - def_list #ä½¿ç”¨å„ç±»è¡¨æ ¼
  - pymdownx.tasklist:
      custom_checkbox: true
  - meta
  - sane_lists
  - pymdownx.magiclink


extra_css:
  - stylesheets/css/card.css
  - stylesheets/css/flink.css
  - mkdocs/css/custom.css
  - mkdocs/css/emoji.css
  - mkdocs/css/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css

  # - https://unpkg.com/katex@0/dist/katex.min.css
  # - attr_list
  # - md_in_html
  # - toc:
  #     permalink: true
  # - pymdownx.highlight:
  #     linenums: true
  #     auto_title: true
  #     line_spans: __span
  #     pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes

extra_javascript:
  # [æ•°å­¦å…¬å¼æ”¯æŒ]
  # https://squidfunk.github.io/mkdocs-material/reference/math/#katex
  - mkdocs/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
